name: lca_algebraic_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip  # Ensure pip is installed
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - six
  - pip:
    - lca_algebraic
